---
- name: Check environment setup
  hosts: linux
  gather_facts: true
 
  tasks:
    - name: Include vars
      ansible.builtin.include_vars:
        dir: group_vars

    - name: Import environment role
      ansible.builtin.import_role:
        name: environment

  post_tasks:
    - name: Debug the outcome
      ansible.builtin.debug:
        msg:
          - "{{ inventory_hostname }} managed successfully "
